### ISSUE TITLE
Want to fix some bugs

### ISSUE THREAD

**Issue by JokerLin1223** [evenrose/CMDIAD#1]
After running the command：”python main.py --method_name DINO+Point_MAE --experiment_note "First experiment with DINO+PointMAE" --save_feature_for_fusion --save_path datasets/patch_lib“

Report an error：
Traceback (most recent call last):
  File "/media/user/3c549a17-7294-45ad-a959-eeb5a3373cf7/lb/CMDIAD-main/main.py", line 182, in <module>
    run_3d_ads(args)
  File "/media/user/3c549a17-7294-45ad-a959-eeb5a3373cf7/lb/CMDIAD-main/main.py", line 24, in run_3d_ads
    model.fit(cls)
  File "/media/user/3c549a17-7294-45ad-a959-eeb5a3373cf7/lb/CMDIAD-main/cmdiad_runner.py", line 46, in fit
    method.add_sample_to_mem_bank(sample, class_name=class_name)
  File "/media/user/3c549a17-7294-45ad-a959-eeb5a3373cf7/lb/CMDIAD-main/feature_extractors/multiple_features.py", line 809, in add_sample_to_mem_bank
    rgb_feature_maps, xyz_feature_maps, center, neighbor_idx, center_idx, interpolated_pc = self(sample[0],
                                                                                            ^^^^^^^^^^^^^^^
  File "/media/user/3c549a17-7294-45ad-a959-eeb5a3373cf7/lb/CMDIAD-main/feature_extractors/features.py", line 128, in __call__
    rgb_feature_maps, xyz_feature_maps, center, ori_idx, center_idx = self.deep_feature_extractor(rgb, xyz)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/CMDIAD/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/CMDIAD/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/user/3c549a17-7294-45ad-a959-eeb5a3373cf7/lb/CMDIAD-main/models/models.py", line 59, in forward
    xyz_features, center, ori_idx, center_idx = self.xyz_backbone(xyz)
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/CMDIAD/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/CMDIAD/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/user/3c549a17-7294-45ad-a959-eeb5a3373cf7/lb/CMDIAD-main/models/models.py", line 355, in forward
    neighborhood, center, ori_idx, center_idx = self.group_divider(pts)
                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/CMDIAD/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/CMDIAD/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/user/3c549a17-7294-45ad-a959-eeb5a3373cf7/lb/CMDIAD-main/models/models.py", line 98, in forward
    center, center_idx = fps(xyz.contiguous(), self.num_group)  # B G 3
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/user/3c549a17-7294-45ad-a959-eeb5a3373cf7/lb/CMDIAD-main/models/models.py", line 76, in fps
    fps_idx = pointnet2_utils.furthest_point_sample(data, number)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/CMDIAD/lib/python3.11/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/CMDIAD/lib/python3.11/site-packages/pointnet2_ops/pointnet2_utils.py", line 54, in forward
    out = _ext.furthest_point_sampling(xyz, npoint)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unknown layout

I use the environment provided by the author completely, but it still prompts the underlying environment error. I would like to ask if anyone has a solution.

**Comment by evenrose** [comment]
Hi, thanks for your interest! I believe this is a problem with the `pointnet2_ops` package. I just found pip used my local cache to install this package. Now I updated the `README.md` and `requirements.txt`. It now works on my another laptop. Don't hesitate to ask if you have more issues. :)

**Comment by JokerLin1223** [comment]
> Hi, thanks for your interest! I believe this is a problem with the `pointnet2_ops` package. I just found pip used my local cache to install this package. Now I updated the `README.md` and `requirements.txt`. It now works on my another laptop. Don't hesitate to ask if you have more issues. :)

Thank you very much. I also think it is a problem with the pointnet2_ops package. I originally used the package of erikwijmans, but later I tried the package you uploaded separately and still had problems. So I don’t know where to make detailed changes, so I left an issue to ask you separately. Thank you very much for your reply. I will continue to try and communicate with you if there are any problems.

**Comment by JokerLin1223** [comment]
After reinstalling the environment, there was no ninja error during the installation of point2net_ops, and the data was processed smoothly, but a ninja problem occurred during the compilation process: "RuntimeError: Ninja is required to load C++ extensions". I directly performed the "pip install ninja" operation, and still reported the error "RuntimeError: Unknown layout". Now I have deleted the ninja package. I would like to ask the author whether the ninja error here is similar to the problem that occurred during the compilation of the point2net_ops package you mentioned earlier. Now I suspect that the Unknown layout problem is caused by the incompatibility of the ninja package version I installed, because the other environments are all configured according to your environment. I am very sorry for the disturbance, but I really want to solve this problem, so I come to bother you again. I am a Chinese. If it is convenient for you, I would also like to add your contact information. Although it may be a bit presumptuous, I am very eager to solve the problem, so I really want to have a deeper communication with you. I apologize for the disturbance.

**Comment by evenrose** [comment]
Hi, for ninja issues, I mentioned it in the pull request of point2net_ops and I attached its link close to the commands.  [pull request of point2net_ops](https://github.com/erikwijmans/Pointnet2_PyTorch/pull/177/files) You can choose to install ninja or forbid the usage of ninja of pytorch extension. And, **DO NOT USE WINDOWS FOR ML**, at least use WSL2. 
For issues of this repo, I recommend using GitHub to share experiences with more fellows. You seem in a hurry and a little frustrated. Maybe email me more information and I'll see what I can help.

**Comment by evenrose** [comment]
> After reinstalling the environment, there was no ninja error during the installation of point2net_ops, and the data was processed smoothly, but a ninja problem occurred during the compilation process: "RuntimeError: Ninja is required to load C++ extensions". I directly performed the "pip install ninja" operation, and still reported the error "RuntimeError: Unknown layout". Now I have deleted the ninja package. I would like to ask the author whether the ninja error here is similar to the problem that occurred during the compilation of the point2net_ops package you mentioned earlier. Now I suspect that the Unknown layout problem is caused by the incompatibility of the ninja package version I installed, because the other environments are all configured according to your environment. I am very sorry for the disturbance, but I really want to solve this problem, so I come to bother you again. I am a Chinese. If it is convenient for you, I would also like to add your contact information. Although it may be a bit presumptuous, I am very eager to solve the problem, so I really want to have a deeper communication with you. I apologize for the disturbance.

Hi, for ninja issues, I mentioned it in the pull request of point2net_ops and I attached its link close to the commands. [pull request of point2net_ops](https://github.com/erikwijmans/Pointnet2_PyTorch/pull/177/files) You can choose to install ninja or forbid the usage of ninja of PyTorch extension. And, DO NOT USE WINDOWS FOR ML, at least use WSL2.
For issues of this repo, I recommend using GitHub to share experiences with more fellows. But you seem in a hurry and a little frustrated. Maybe email me more of your information and I'll see what I can help. I'm the first author of the paper.

**Comment by JokerLin1223** [comment]
> > After reinstalling the environment, there was no ninja error during the installation of point2net_ops, and the data was processed smoothly, but a ninja problem occurred during the compilation process: "RuntimeError: Ninja is required to load C++ extensions". I directly performed the "pip install ninja" operation, and still reported the error "RuntimeError: Unknown layout". Now I have deleted the ninja package. I would like to ask the author whether the ninja error here is similar to the problem that occurred during the compilation of the point2net_ops package you mentioned earlier. Now I suspect that the Unknown layout problem is caused by the incompatibility of the ninja package version I installed, because the other environments are all configured according to your environment. I am very sorry for the disturbance, but I really want to solve this problem, so I come to bother you again. I am a Chinese. If it is convenient for you, I would also like to add your contact information. Although it may be a bit presumptuous, I am very eager to solve the problem, so I really want to have a deeper communication with you. I apologize for the disturbance.
> 
> Hi, for ninja issues, I mentioned it in the pull request of point2net_ops and I attached its link close to the commands. [pull request of point2net_ops](https://github.com/erikwijmans/Pointnet2_PyTorch/pull/177/files) You can choose to install ninja or forbid the usage of ninja of PyTorch extension. And, DO NOT USE WINDOWS FOR ML, at least use WSL2. For issues of this repo, I recommend using GitHub to share experiences with more fellows. But you seem in a hurry and a little frustrated. Maybe email me more of your information and I'll see what I can help. I'm the first author of the paper.

Thank you very much! The problem has been solved! I reinstalled the environment and found that the original g++ version was 7.5. After changing the g++ version to 9.0 and recompiling the pointnet2_ops package, it ran successfully. Special thanks to the author for his help.
