### ISSUE TITLE
File missing?

### ISSUE THREAD

**Issue by YubingChan** [evenrose/CMDIAD#2]
Hi, thanks for your outstanding work!  However, when I tried to learn this work, I found that some files were missing.
Like in features.py 
line 17: [from models.feature_fusion import FeatureFusionBlock](https://github.com/evenrose/CMDIAD/blob/a701fe570130f4e11a5bf2d7aeaba0c2420a9815/feature_extractors/features.py#L17)
line 18: [from models.feature_decoupling import FeatureDecouplingBlock](https://github.com/evenrose/CMDIAD/blob/a701fe570130f4e11a5bf2d7aeaba0c2420a9815/feature_extractors/features.py#L18) 
Are there have no feature_fusion and feature_decoupling files in models folder?
Looking forward to your reply.

**Comment by evenrose** [comment]
Hi, thanks for your interest! There were some issues when I updated the repo to a new version. Now it should work properly. Please refresh the repo and sorry for any inconvenience.

**Comment by YubingChan** [comment]
> Hi, thanks for your interest! There were some issues when I updated the repo to a new version. Now it should work properly. Please refresh the repo and sorry for any inconvenience.

Thanks a lot, this repo is ready to run. By the way, what type of CPU and GPU are you using? I may not have enough CPU and GPU memory to run fully.

**Comment by evenrose** [comment]
> > Hi, thanks for your interest! There were some issues when I updated the repo to a new version. Now it should work properly. Please refresh the repo and sorry for any inconvenience.
> 
> Thanks a lot, this repo is ready to run. By the way, what type of CPU and GPU are you using? I may not have enough CPU and GPU memory to run fully.

I tried a6000 v100 and a100 40g. I think it is fine if you have anything better than 24g. The best performance is from feature to feature distillation, which is quite lightweight. If you just want inference, a gpu with 8g vRam is enough.

**Comment by YubingChan** [comment]
> > > Hi, thanks for your interest! There were some issues when I updated the repo to a new version. Now it should work properly. Please refresh the repo and sorry for any inconvenience.
> > 
> > 
> > Thanks a lot, this repo is ready to run. By the way, what type of CPU and GPU are you using? I may not have enough CPU and GPU memory to run fully.
> 
> I tried a6000 v100 and a100 40g. I think it is fine if you have anything better than 24g. The best performance is from feature to feature distillation, which is quite lightweight. If you just want inference, a gpu with 8g vRam is enough.

understand, thanks again！
